FROM node:20-slim

ARG NEXT_PUBLIC_SLEEPAGENT_API_BASE_URL=http://127.0.0.1:18000
ARG NEXT_PUBLIC_SLEEPAGENT_MOCK_MODE=false

ENV NEXT_TELEMETRY_DISABLED=1 \
    NEXT_PUBLIC_SLEEPAGENT_API_BASE_URL=${NEXT_PUBLIC_SLEEPAGENT_API_BASE_URL} \
    NEXT_PUBLIC_SLEEPAGENT_MOCK_MODE=${NEXT_PUBLIC_SLEEPAGENT_MOCK_MODE}

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

COPY frontend ./
RUN npm run build

EXPOSE 18510

CMD ["npm", "run", "start"]
