from __future__ import annotations

from .contracts import (
    HabitAnswerDisposition,
    HabitAnswerType,
    HabitConceptDefinition,
    HabitPersistenceEligibility,
    HabitQuestionTrigger,
    HabitRespondentRule,
)


_PROFILE_TRIGGERS = (
    HabitQuestionTrigger.OPTIONAL_LIGHT_INTAKE,
    HabitQuestionTrigger.EXPLICIT_HABIT_QUESTION,
    HabitQuestionTrigger.DECISION_RELEVANT_GAP,
    HabitQuestionTrigger.STALE_FACT_NEEDED,
    HabitQuestionTrigger.SOURCE_CONFLICT,
    HabitQuestionTrigger.EXPLICIT_PROFILE_REVIEW,
)
_NONANSWER_DISPOSITIONS = (
    HabitAnswerDisposition.ANSWERED,
    HabitAnswerDisposition.VARIABLE,
    HabitAnswerDisposition.NOT_APPLICABLE,
    HabitAnswerDisposition.UNKNOWN,
    HabitAnswerDisposition.PREFER_NOT_TO_ANSWER,
    HabitAnswerDisposition.SKIPPED,
    HabitAnswerDisposition.NEVER_ASK,
)


def _habit_concept(**values) -> HabitConceptDefinition:
    cooldown_hours = values.pop("cooldown_hours", 168)
    return HabitConceptDefinition(
        reviewer_ref="sleep-habit-profile-plan:approved-round-5",
        content_version="sleep-habit-concepts.zh-CN.v1",
        domain_review_status="approved",
        cooldown_hours=cooldown_hours,
        triggers=_PROFILE_TRIGGERS,
        allowed_dispositions=_NONANSWER_DISPOSITIONS,
        **values,
    )


DEFAULT_HABIT_CONCEPTS = (
    _habit_concept(
        concept_id="habit.primary_goal",
        version="1.0.0",
        domain="personal_goal",
        purpose="只在当前照护需要时了解老人最希望改善的非临床目标。",
        canonical_question="当前最希望改善哪一项睡眠相关体验？",
        elder_text="您现在最想先改善哪一件睡眠方面的事？",
        answer_type=HabitAnswerType.CHOICE,
        options=("更规律", "白天更有精神", "夜里少受打扰", "暂时没有", "不固定"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("care_goal", "care_burden"),
    ),
    _habit_concept(
        concept_id="habit.schedule_constraint",
        version="1.0.0",
        domain="schedule_constraint",
        purpose="识别雷达无法观察、会限制低风险行动安排的作息约束。",
        canonical_question="是否有必须遵守的起床或晚间时间约束？",
        elder_text="平时有没有必须按时起床或晚上必须做的事情？",
        answer_type=HabitAnswerType.CHOICE,
        options=("没有固定约束", "必须早起", "夜间需照护他人", "固定活动", "不固定"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=180,
        affects_decisions=("care_timing", "schedule_interpretation"),
    ),
    _habit_concept(
        concept_id="habit.nap_pattern",
        version="1.0.0",
        domain="nap",
        purpose="在午睡可能改变日间影响解释或行动安排时提供上下文。",
        canonical_question="通常是否午睡？",
        elder_text="您平时会午睡吗？",
        observer_text="您实际观察到老人平时会午睡吗？",
        answer_type=HabitAnswerType.CHOICE,
        options=("通常不午睡", "偶尔午睡", "多数天午睡", "不固定"),
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("daytime_context", "care_timing"),
    ),
    _habit_concept(
        concept_id="habit.nap_duration_minutes",
        version="1.0.0",
        domain="nap",
        purpose="在确有决策需要时记录大致午睡时长，不要求精确日记。",
        canonical_question="通常一次午睡大约多少分钟？",
        elder_text="一般一次午睡大约多久？",
        observer_text="您观察到老人一次午睡通常大约多久？",
        answer_type=HabitAnswerType.BOUNDED_NUMBER,
        unit="minute",
        minimum=0,
        maximum=240,
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("daytime_context", "care_timing"),
    ),
    _habit_concept(
        concept_id="habit.pre_sleep_behavior",
        version="1.0.0",
        domain="pre_sleep_behavior",
        purpose="只登记会影响当前解释或低风险行动的重复睡前行为。",
        canonical_question="睡前通常进行哪类活动？",
        elder_text="睡前通常会做什么？",
        answer_type=HabitAnswerType.CHOICE,
        options=("看屏幕", "阅读", "洗漱", "聊天", "放松活动", "不固定"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("care_action_selection", "evidence_alternative"),
    ),
    _habit_concept(
        concept_id="habit.environment_preference",
        version="1.0.0",
        domain="environment",
        purpose="在环境相关解释或行动中保留本人的中性偏好。",
        canonical_question="睡觉时更偏好怎样的环境？",
        elder_text="睡觉时，您更喜欢怎样的光线和声音？",
        answer_type=HabitAnswerType.CHOICE,
        options=("较暗安静", "留一点光", "有背景声音", "没有固定偏好"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=180,
        affects_decisions=("care_environment",),
    ),
    _habit_concept(
        concept_id="habit.stimulant_timing",
        version="1.0.0",
        domain="stimulant_timing",
        purpose="仅记录咖啡或浓茶相对睡前的时间模式，不形成好坏标签。",
        canonical_question="咖啡或浓茶通常在什么时间饮用？",
        elder_text="平时咖啡或浓茶一般在什么时候喝？",
        answer_type=HabitAnswerType.CHOICE,
        options=("通常不喝", "上午", "下午", "晚间", "不固定"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("evidence_alternative", "care_action_selection"),
    ),
    _habit_concept(
        concept_id="habit.sleep_satisfaction_recent",
        version="1.0.0",
        domain="subjective_context",
        purpose="记录老人近期主观满意度，只作短时上下文。",
        canonical_question="最近一周对自己的睡眠总体感受如何？",
        elder_text="最近一周，您对自己的睡眠感觉怎么样？",
        answer_type=HabitAnswerType.SCALE,
        options=("满意", "还可以", "不太满意", "很不满意"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=14,
        affects_decisions=("subjective_context", "care_goal"),
    ),
    _habit_concept(
        concept_id="habit.observed_snoring",
        version="1.0.0",
        domain="observable_night_behavior",
        purpose="保留本人或家属实际观察，不作为诊断或排除风险的结论。",
        canonical_question="近期是否实际观察到明显打鼾或憋醒？",
        elder_text="近期您知道自己有明显打鼾或憋醒吗？",
        observer_text="近期您是否亲自听到或看到老人明显打鼾或憋醒？",
        answer_type=HabitAnswerType.CHOICE,
        options=("观察到", "没有观察到", "偶尔", "不清楚"),
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=30,
        affects_decisions=("evidence_uncertainty", "safety_route"),
        negative_answer_requires_observation_opportunity=True,
        safety_route_enabled=True,
    ),
    _habit_concept(
        concept_id="habit.night_toileting_pattern",
        version="1.0.0",
        domain="night_activity",
        purpose="解释夜间离床事件是否符合本人通常如厕模式，不用于否决安全红旗。",
        canonical_question="通常是否会因如厕在夜间离床？",
        elder_text="您平时夜里会起床去卫生间吗？",
        observer_text="您亲自观察到老人平时会因如厕在夜间离床吗？",
        answer_type=HabitAnswerType.CHOICE,
        options=("通常不会", "偶尔", "多数夜晚", "不固定"),
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("night_event_interpretation", "evidence_alternative"),
    ),
    _habit_concept(
        concept_id="habit.night_out_of_bed_frequency",
        version="1.0.0",
        domain="night_activity",
        purpose="记录通常每夜离床次数范围的代表值，辅助相对个人基线解释。",
        canonical_question="通常每夜离床大约几次？",
        elder_text="平时一晚上大约会起床几次？",
        observer_text="您亲自观察到老人平时一晚上大约离床几次？",
        answer_type=HabitAnswerType.BOUNDED_NUMBER,
        unit="count_per_night",
        minimum=0,
        maximum=20,
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("night_event_interpretation", "trend_comparison"),
    ),
    _habit_concept(
        concept_id="habit.night_out_of_bed_time_window",
        version="1.0.0",
        domain="night_activity",
        purpose="保留通常夜间离床的大致时段，不要求精确时间日记。",
        canonical_question="通常在夜间什么时段离床？",
        elder_text="平时夜里大约几点会起床？说个大概时段就可以。",
        observer_text="您亲自观察到老人通常在夜里什么时段离床？",
        answer_type=HabitAnswerType.SHORT_TEXT,
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("night_event_interpretation", "care_timing"),
    ),
    _habit_concept(
        concept_id="habit.night_out_of_bed_duration_minutes",
        version="1.0.0",
        domain="night_activity",
        purpose="记录通常一次夜间离床的大致时长，用于识别明显延长。",
        canonical_question="通常一次夜间离床大约持续多少分钟？",
        elder_text="平时夜里一次起床大约多久会回床？",
        observer_text="您亲自观察到老人一次夜间离床通常持续多久？",
        answer_type=HabitAnswerType.BOUNDED_NUMBER,
        unit="minute",
        minimum=0,
        maximum=240,
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("night_event_interpretation", "risk_attention"),
    ),
    _habit_concept(
        concept_id="habit.night_activity_assistance_need",
        version="1.0.0",
        domain="night_activity",
        purpose="决定夜间活动是静默观察、设备支持还是需要照护协同。",
        canonical_question="通常夜间离床能否自行完成？",
        elder_text="平时夜里起床，您一般能自己完成还是需要帮忙？",
        observer_text="您亲自观察到老人夜间离床通常是否需要协助？",
        answer_type=HabitAnswerType.CHOICE,
        options=("通常可自行完成", "偶尔需要协助", "通常需要协助", "不固定"),
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=90,
        affects_decisions=("care_modality", "family_coordination", "risk_context"),
    ),
    _habit_concept(
        concept_id="habit.observed_night_leaving",
        version="1.0.0",
        domain="observable_night_behavior",
        purpose="区分老人自述与家属直接观察到的夜间离床模式。",
        canonical_question="近期是否直接观察到老人夜间离床？",
        elder_text="近期您记得自己夜里离开床吗？",
        observer_text="近期您是否亲自观察到老人夜间离床？",
        answer_type=HabitAnswerType.CHOICE,
        options=("观察到", "没有观察到", "偶尔", "不清楚"),
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=30,
        affects_decisions=("evidence_uncertainty", "night_event_interpretation"),
        negative_answer_requires_observation_opportunity=True,
    ),
    _habit_concept(
        concept_id="habit.delivery_timing_preference",
        version="1.0.0",
        domain="care_delivery_preference",
        purpose="决定非紧急反馈应立即给出还是延至早晨。",
        canonical_question="非紧急睡眠提醒希望何时收到？",
        elder_text="不是紧急情况时，您希望当时提醒，还是早晨再说？",
        answer_type=HabitAnswerType.CHOICE,
        options=("立即", "早晨", "视情况", "不希望提醒"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=180,
        affects_decisions=("care_timing", "care_burden"),
    ),
    _habit_concept(
        concept_id="habit.delivery_modality_preference",
        version="1.0.0",
        domain="care_delivery_preference",
        purpose="决定非紧急照护通过语音、灯光或静默记录交付。",
        canonical_question="非紧急提醒更接受哪种方式？",
        elder_text="不是紧急情况时，您更接受语音、灯光，还是先不打扰？",
        answer_type=HabitAnswerType.CHOICE,
        options=("语音", "灯光", "静默记录", "没有固定偏好"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=180,
        affects_decisions=("care_modality", "care_burden"),
    ),
    _habit_concept(
        concept_id="habit.interruption_burden",
        version="1.0.0",
        domain="care_delivery_preference",
        purpose="限制非紧急主动交互的打扰负担。",
        canonical_question="能够接受多大程度的夜间提醒打扰？",
        elder_text="夜里如果不是紧急情况，您能接受多大程度的提醒？",
        answer_type=HabitAnswerType.CHOICE,
        options=("不打扰", "轻微", "一般", "可以明显提醒"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=180,
        affects_decisions=("care_burden", "care_modality"),
    ),
    _habit_concept(
        concept_id="habit.family_notification_preference",
        version="1.0.0",
        domain="care_delivery_preference",
        purpose="决定非紧急事件是否建议家属通知；安全升级仍由硬策略控制。",
        canonical_question="非紧急夜间事件是否希望通知家属？",
        elder_text="不是紧急情况时，夜里有情况要不要通知家里人？",
        answer_type=HabitAnswerType.CHOICE,
        options=("不通知", "早晨通知", "当时通知", "视情况"),
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=180,
        affects_decisions=("family_coordination", "care_burden"),
    ),
    _habit_concept(
        concept_id="habit.quiet_hours",
        version="1.0.0",
        domain="care_delivery_preference",
        purpose="冻结老人希望保持安静的时段，供设备策略和保守默认值使用。",
        canonical_question="希望保持安静、不被非紧急提醒打扰的时段是什么？",
        elder_text="您希望从几点到几点尽量不被非紧急提醒打扰？",
        answer_type=HabitAnswerType.SHORT_TEXT,
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=180,
        affects_decisions=("quiet_hours", "care_timing"),
    ),
    _habit_concept(
        concept_id="habit.voice_volume_preference",
        version="1.0.0",
        domain="care_delivery_preference",
        purpose="限制非紧急语音提醒音量，安全升级可按设备策略覆盖。",
        canonical_question="语音提醒音量偏好是多少？",
        elder_text="如果用语音提醒，您希望音量大约是多少？",
        answer_type=HabitAnswerType.BOUNDED_NUMBER,
        unit="percent",
        minimum=0,
        maximum=100,
        respondent_rule=HabitRespondentRule.ELDER_ONLY,
        persistence=HabitPersistenceEligibility.PROFILE_ELIGIBLE,
        valid_for_days=180,
        affects_decisions=("voice_volume", "care_burden"),
    ),
    _habit_concept(
        concept_id="habit.device_position_last_night",
        version="1.0.0",
        domain="data_quality",
        purpose="只用于当前单夜数据质量解释，绝不形成长期习惯。",
        canonical_question="昨晚设备位置是否变化？",
        elder_text="昨晚床边设备的位置动过吗？",
        observer_text="昨晚雷达设备位置或遮挡情况是否变化？",
        answer_type=HabitAnswerType.CHOICE,
        options=("没有", "可能移动过", "不清楚"),
        respondent_rule=HabitRespondentRule.ELDER_OR_OBSERVER,
        persistence=HabitPersistenceEligibility.EPISODE_ONLY,
        valid_for_days=1,
        cooldown_hours=0,
        affects_decisions=("data_quality",),
    ),
)

HABIT_CONCEPT_REGISTRY = {
    (item.concept_id, item.version): item for item in DEFAULT_HABIT_CONCEPTS
}


__all__ = [
    "DEFAULT_HABIT_CONCEPTS",
    "HABIT_CONCEPT_REGISTRY",
]
