import type { SleepAnalysisMock } from "@/lib/types";

export const sleepAnalysis: SleepAnalysisMock = {
  patient: {
    name: "张阿姨",
    age: 68,
    recordDate: "2026-01-02",
    source: "SHHS / PSG 演示记录",
    durationMinutes: 480,
  },
  defaultTask:
    "分析张阿姨 2026-01-02 的 PSG 睡眠记录，判断睡眠呼吸风险，并生成适合老人、家属和医生的报告。",
  taskThread: {
    id: "task-20260102-psg-risk",
    title: "张阿姨 PSG 睡眠呼吸风险分析",
    userGoal: "分析张阿姨 2026-01-02 的 PSG 睡眠记录，判断睡眠呼吸风险，并生成适合老人、家属和医生的报告。",
    status: "completed",
    patientId: "patient-zhang-ayi",
    recordId: "shhs1-200001",
    createdAt: "2026-01-02 07:20",
    plan: [
      {
        id: "load_record",
        title: "读取 PSG 数据",
        agent: "数据读取 Agent",
        description: "读取记录元数据、通道信息和 480 分钟 PSG 窗口。",
        status: "completed",
        durationMs: 620,
        toolCalls: [
          {
            id: "tool-load-metadata",
            toolName: "PSG Metadata Reader",
            inputSummary: "record_id=shhs1-200001",
            outputSummary: "读取 480 分钟记录，关键通道完整。",
            status: "success",
            durationMs: 240,
          },
        ],
      },
      {
        id: "quality_check",
        title: "检查数据质量",
        agent: "质量检查 Agent",
        description: "检查 EEG/EOG/EMG、Airflow、胸腹呼吸努力和 SpO2 通道可用性。",
        status: "completed",
        durationMs: 740,
        toolCalls: [
          {
            id: "tool-quality-gate",
            toolName: "Signal Quality Gate",
            inputSummary: "关键通道、记录时长、基础异常值范围。",
            outputSummary: "数据质量良好，可进入睡眠分期和呼吸事件分析。",
            status: "success",
            durationMs: 360,
          },
        ],
      },
      {
        id: "sleep_staging",
        title: "识别睡眠阶段",
        agent: "睡眠分期 Agent",
        description: "识别 Wake / REM / NREM，并计算睡眠效率。",
        status: "completed",
        durationMs: 1180,
        toolCalls: [
          {
            id: "tool-yasa",
            toolName: "YASA Adapter",
            inputSummary: "EEG / EOG / EMG epoch 序列。",
            outputSummary: "睡眠效率 88.4%，总睡眠约 424.5 分钟。",
            status: "success",
            durationMs: 820,
          },
        ],
      },
      {
        id: "respiratory_detection",
        title: "检测呼吸异常",
        agent: "呼吸事件检测 Agent",
        description: "检测正常呼吸、低通气和疑似呼吸暂停事件。",
        status: "completed",
        durationMs: 1640,
        toolCalls: [
          {
            id: "tool-resp-model",
            toolName: "1D-CNN + BiLSTM Boundary",
            inputSummary: "Airflow、胸腹呼吸努力、SpO2 候选窗口。",
            outputSummary: "低通气 27 次，疑似呼吸暂停 15 次。",
            status: "success",
            durationMs: 1120,
          },
          {
            id: "tool-event-extractor",
            toolName: "Respiratory Event Extractor",
            inputSummary: "模型边界与候选事件窗口。",
            outputSummary: "聚合 AHI 5.94，最低 SpO2 94.2%。",
            status: "success",
            durationMs: 280,
          },
        ],
      },
      {
        id: "risk_assessment",
        title: "综合风险判断",
        agent: "风险评估 Agent",
        description: "结合 AHI、事件数量、血氧和历史趋势形成风险结论。",
        status: "completed",
        durationMs: 690,
        toolCalls: [
          {
            id: "tool-risk-rule",
            toolName: "Risk Rule Engine",
            inputSummary: "AHI=5.94、暂停=15、低通气=27、最低 SpO2=94.2%。",
            outputSummary: "输出中等风险，建议连续观察 3-7 晚。",
            status: "success",
            durationMs: 410,
          },
        ],
      },
      {
        id: "medical_rag",
        title: "检索医学知识",
        agent: "医学知识检索 Agent",
        description: "检索 AHI、OSA 风险、安全边界和家庭观察依据。",
        status: "completed",
        durationMs: 760,
        toolCalls: [
          {
            id: "tool-rag",
            toolName: "Local Medical Knowledge",
            inputSummary: "AHI 解释、OSA 风险提示、就医边界。",
            outputSummary: "返回 3 条本地医学依据片段。",
            status: "success",
            durationMs: 430,
          },
        ],
      },
      {
        id: "report_generation",
        title: "生成多角色报告",
        agent: "报告生成 Agent",
        description: "生成老人、家属、医生和技术说明 Artifact。",
        status: "completed",
        durationMs: 920,
        toolCalls: [
          {
            id: "tool-report-format",
            toolName: "Role Report Formatter",
            inputSummary: "风险摘要、证据链、角色和安全声明。",
            outputSummary: "创建 4 个报告 Artifact。",
            status: "success",
            durationMs: 610,
          },
        ],
      },
      {
        id: "care_plan",
        title: "创建关怀计划建议",
        agent: "关怀计划 Agent",
        description: "将单晚风险转成 7 天观察和提醒建议。",
        status: "completed",
        durationMs: 520,
        toolCalls: [
          {
            id: "tool-care-plan",
            toolName: "Care Plan Builder",
            inputSummary: "风险结论、家属关注点和趋势摘要。",
            outputSummary: "生成 7 天观察计划草稿。",
            status: "success",
            durationMs: 330,
          },
        ],
      },
      {
        id: "chat_context",
        title: "准备问答上下文",
        agent: "对话问答 Agent",
        description: "准备当前记录、历史趋势和安全边界，用于后续追问和操作。",
        status: "completed",
        durationMs: 540,
        toolCalls: [
          {
            id: "tool-chat-context",
            toolName: "Dialogue Context Builder",
            inputSummary: "当前任务、Artifact、趋势和医学依据。",
            outputSummary: "Chat 可触发报告修改、关怀计划和医生摘要。",
            status: "success",
            durationMs: 310,
          },
        ],
      },
    ],
    events: [
      {
        id: "evt-001",
        type: "task_created",
        title: "任务已创建",
        message: "用户请求分析 2026-01-02 PSG 记录并生成多角色报告。",
        timestamp: "07:20:00",
      },
      {
        id: "evt-002",
        type: "plan_created",
        title: "计划已生成",
        message: "SleepAgent 生成 9 步执行计划，等待用户确认。",
        timestamp: "07:20:04",
      },
      {
        id: "evt-003",
        type: "step_started",
        stepId: "load_record",
        title: "开始读取记录",
        message: "正在读取 PSG 元数据和 480 分钟记录窗口。",
        timestamp: "07:20:10",
      },
      {
        id: "evt-004",
        type: "tool_called",
        stepId: "respiratory_detection",
        title: "调用呼吸事件模型",
        message: "1D-CNN + BiLSTM Boundary 正在检测候选呼吸异常窗口。",
        timestamp: "07:20:19",
        payload: { toolName: "1D-CNN + BiLSTM Boundary", durationMs: 1120 },
      },
      {
        id: "evt-005",
        type: "finding_created",
        stepId: "respiratory_detection",
        title: "发现呼吸异常",
        message: "检测到疑似呼吸暂停 15 次，低通气 27 次，AHI 约 5.94。",
        timestamp: "07:20:23",
      },
      {
        id: "evt-006",
        type: "artifact_created",
        stepId: "report_generation",
        title: "报告 Artifact 已创建",
        message: "已生成老人、家属、医生和技术说明四类报告。",
        timestamp: "07:20:31",
      },
      {
        id: "evt-007",
        type: "artifact_created",
        stepId: "care_plan",
        title: "关怀计划 Artifact 已创建",
        message: "已创建未来 7 天观察计划建议，等待用户确认是否开启。",
        timestamp: "07:20:35",
      },
      {
        id: "evt-008",
        type: "task_completed",
        title: "任务完成",
        message: "SleepAgent 已完成风险判断、Artifact 生成和问答上下文准备。",
        timestamp: "07:20:40",
      },
    ],
    artifacts: [
      {
        id: "artifact-risk",
        type: "risk_summary",
        title: "今日风险结论",
        status: "ready",
        content: "本次 PSG 记录提示中等睡眠呼吸风险。AHI 约 5.94，疑似呼吸暂停 15 次，低通气 27 次，最低 SpO2 94.2%。建议连续观察 3-7 晚，并结合打鼾、憋醒和白天困倦情况判断是否咨询医生。",
        createdByStepId: "risk_assessment",
        updatedAt: "07:20:25",
      },
      {
        id: "artifact-evidence",
        type: "evidence_chain",
        title: "风险证据链",
        status: "ready",
        content: "关键证据包括：AHI 达到轻度异常范围；低通气和疑似暂停事件数量需要关注；最低 SpO2 暂未见明显低氧；单晚自动分析不能替代临床诊断。",
        createdByStepId: "medical_rag",
        updatedAt: "07:20:28",
      },
      {
        id: "artifact-elder",
        type: "elder_report",
        title: "老人易懂版报告",
        status: "ready",
        content: "昨晚整体睡眠还可以，但 SleepAgent 发现一些呼吸不稳定的信号。先不用紧张，建议连续观察几晚。如果经常打鼾、憋醒或白天犯困，可以让家人陪同咨询医生。",
        createdByStepId: "report_generation",
        updatedAt: "07:20:31",
      },
      {
        id: "artifact-family",
        type: "family_report",
        title: "家属照护版报告",
        status: "ready",
        content: "本次记录提示中等风险。建议家属关注张阿姨是否伴随明显打鼾、憋醒或白天困倦，并连续观察 3-7 晚。如连续异常，建议预约睡眠医学或呼吸科咨询。",
        createdByStepId: "report_generation",
        updatedAt: "07:20:31",
      },
      {
        id: "artifact-doctor",
        type: "doctor_report",
        title: "医生专业版报告",
        status: "ready",
        content: "患者 68 岁，PSG 记录 480 分钟。自动分析显示 AHI 5.94/h，sleep efficiency 88.4%，suspected apnea 15，hypopnea 27，min SpO2 94.2%。建议结合完整 PSG、症状和临床信息综合判断。",
        createdByStepId: "report_generation",
        updatedAt: "07:20:31",
      },
      {
        id: "artifact-tech",
        type: "technical_report",
        title: "技术说明 Artifact",
        status: "ready",
        content: "当前 React 前端使用 mock Task Thread 模拟未来 SSE/WebSocket 事件流。Agent 图：LoadRecord → QualityCheck → SleepStaging → RespiratoryDetection → RiskAssessment → MedicalRag → ReportGeneration → CarePlan → ChatContext。",
        createdByStepId: "report_generation",
        updatedAt: "07:20:31",
      },
      {
        id: "artifact-trend",
        type: "trend_interpretation",
        title: "趋势解释",
        status: "ready",
        content: "最近 7 天 AHI 大致处于 5-8 区间，睡眠效率整体良好，最低 SpO2 暂未见明显低氧。当前重点是连续观察呼吸稳定性和症状变化。",
        createdByStepId: "risk_assessment",
        updatedAt: "07:20:33",
      },
      {
        id: "artifact-care",
        type: "care_plan",
        title: "7 天关怀计划",
        status: "draft",
        content: "未来 7 天观察 AHI、最低 SpO2、疑似呼吸暂停次数，以及是否存在打鼾、憋醒、白天困倦。关键动作需要用户确认后开启。",
        createdByStepId: "care_plan",
        updatedAt: "07:20:35",
      },
    ],
    nextActions: [
      {
        id: "next-open-care",
        label: "确认开启 7 天观察",
        description: "开启前需要用户确认提醒对象和提醒方式。",
        actionType: "care_plan",
        target: "care_plan",
        requiresConfirmation: true,
      },
      {
        id: "next-doctor-summary",
        label: "生成医生就诊摘要",
        description: "基于医生专业版 Artifact 生成门诊沟通摘要。",
        actionType: "export",
        target: "doctor_report",
        requiresConfirmation: true,
      },
      {
        id: "next-revise-elder",
        label: "把报告写得更简单",
        description: "修改老人易懂版 Artifact 的语气和长度。",
        actionType: "revise",
        target: "elder_report",
      },
    ],
  },
  taskHistory: [
    {
      id: "task-20260102-psg-risk",
      title: "张阿姨 PSG 睡眠呼吸风险分析",
      userGoal: "判断睡眠呼吸风险并生成多角色报告。",
      status: "completed",
      patientId: "patient-zhang-ayi",
      recordId: "shhs1-200001",
      createdAt: "2026-01-02 07:20",
      plan: [],
      events: [],
      artifacts: [],
      nextActions: [],
    },
    {
      id: "task-20260101-trend",
      title: "最近 7 天趋势复盘",
      userGoal: "比较最近 7 天 AHI、血氧和睡眠效率趋势。",
      status: "completed",
      patientId: "patient-zhang-ayi",
      recordId: "trend-7d",
      createdAt: "2026-01-01 08:10",
      plan: [],
      events: [],
      artifacts: [],
      nextActions: [],
    },
  ],
  taskTemplates: [
    {
      id: "last-night",
      title: "分析昨晚睡眠记录",
      description: "读取本次 PSG 记录并给出风险结论。",
      prompt: "分析张阿姨 2026-01-02 的 PSG 睡眠记录，判断昨晚睡眠呼吸风险。",
    },
    {
      id: "care",
      title: "判断是否需要就医",
      description: "结合指标、症状线索和安全边界给出建议。",
      prompt: "判断张阿姨这次睡眠记录是否需要尽快就医，并说明需要连续观察哪些症状。",
    },
    {
      id: "doctor-report",
      title: "生成给医生看的报告",
      description: "整理关键指标、事件和就诊摘要。",
      prompt: "生成给医生看的睡眠呼吸风险摘要，保留 AHI、事件数量、血氧和证据链。",
    },
    {
      id: "weekly-trend",
      title: "比较最近 7 天趋势",
      description: "查看 AHI、睡眠效率和血氧是否持续变化。",
      prompt: "比较张阿姨最近 7 天睡眠趋势，判断风险是否连续升高。",
    },
    {
      id: "ahi",
      title: "解释 AHI 为什么升高",
      description: "用当前记录解释风险来源。",
      prompt: "解释这次 AHI 为什么升高，并说明疑似呼吸暂停和低通气的影响。",
    },
  ],
  roleContent: {
    elder: {
      headline: "昨晚整体睡眠还可以，但呼吸有些不稳定。先不用紧张，建议连续观察几晚。",
      riskConclusion: "今晚睡眠呼吸风险为中等，当前没有明显低氧信号。",
      primaryReason: "系统看到夜里有一些呼吸变浅或暂停的片段，所以给出提醒。",
      nextAction: "先连续观察 3 到 7 晚。如果经常憋醒、打鼾明显或白天很困，再请家人陪同咨询医生。",
      recommendedActions: ["继续观察几晚", "记录是否打鼾或憋醒", "让家人了解这份摘要"],
      defaultReportId: "elder",
      chatSuggestions: ["为什么是中等风险？", "我需要担心吗？", "今晚睡觉要注意什么？", "什么时候需要告诉家人？"],
      metricDepth: "simple",
    },
    family: {
      headline: "建议家属关注是否伴随打鼾、憋醒、白天犯困，并连续观察 3-7 晚。",
      riskConclusion: "本次记录提示中等风险，建议纳入家庭观察计划。",
      primaryReason: "AHI 约 5.9，疑似暂停 15 次、低通气 27 次，提示夜间呼吸稳定性下降。",
      nextAction: "建议家属记录夜间鼾声、憋醒、白天精神状态，并在连续异常时预约睡眠医学或呼吸科咨询。",
      recommendedActions: ["开启 7 天观察计划", "生成家属提醒文案", "准备医生就诊摘要"],
      defaultReportId: "family",
      chatSuggestions: ["需要去医院吗？", "家属这几天要观察什么？", "AHI 是什么？", "怎么把报告给医生看？"],
      metricDepth: "care",
    },
    doctor: {
      headline:
        "AHI 5.94，疑似呼吸暂停 15 次，低通气 27 次，最低 SpO2 94.2%，建议结合完整 PSG 与临床症状判断。",
      riskConclusion: "单晚自动分析提示轻度 OSA 风险区间，血氧最低值暂未见明显低氧。",
      primaryReason: "AHI=5.94/h，suspected apnea=15，hypopnea=27，sleep efficiency=88.4%。",
      nextAction: "建议结合原始 PSG、事件分布、睡姿、BMI、打鼾/憋醒/日间嗜睡等临床信息综合判断。",
      recommendedActions: ["查看证据链", "生成医生就诊摘要", "查看技术说明"],
      defaultReportId: "doctor",
      chatSuggestions: ["列出关键 PSG 指标", "AHI 5.94 如何解释？", "血氧证据是否支持高风险？", "生成医生就诊摘要"],
      metricDepth: "clinical",
    },
  },
  riskLevel: "moderate",
  primaryReason: "AHI 约 5.9，处于轻度异常范围，同时存在疑似呼吸暂停和低通气事件。",
  nextAction: "建议连续观察 3 到 7 晚，并记录打鼾、憋醒、白天困倦等症状。",
  metrics: [
    {
      key: "ahi",
      label: "AHI",
      value: "5.94",
      status: "轻度异常边缘",
      description: "每小时疑似呼吸异常次数。",
      reference: "低于 5 通常较稳定，5 到 15 为轻度异常范围。",
      roleExplanations: {
        elder: "可以理解为一小时里呼吸不太顺的次数，当前只是轻度提醒。",
        family: "这是判断睡眠呼吸风险的核心指标，建议结合几晚趋势一起看。",
        doctor: "AHI=5.94/h，处于轻度异常区间，需结合事件分布和症状判断临床意义。",
      },
    },
    {
      key: "efficiency",
      label: "睡眠效率",
      value: "88.4%",
      status: "较好",
      description: "睡眠时间占总记录时间的比例。",
      reference: "大于 85% 通常提示睡眠连续性较好。",
      roleExplanations: {
        elder: "多数时间都睡着了，这一点总体不错。",
        family: "睡眠连续性尚可，当前主要问题不在睡不着，而在呼吸稳定性。",
        doctor: "Sleep efficiency=88.4%，记录可用于后续事件解释。",
      },
    },
    {
      key: "sleep",
      label: "总睡眠",
      value: "424.5 min",
      status: "可用于分析",
      description: "本次记录中处于睡眠阶段的总时长。",
      reference: "需要结合记录质量与症状判断。",
      roleExplanations: {
        elder: "这次记录时间足够，结果有参考价值。",
        family: "睡眠时长足够支撑本次风险判断。",
        doctor: "Total sleep time=424.5 min，记录总时长 480 min。",
      },
    },
    {
      key: "apnea",
      label: "疑似呼吸暂停",
      value: "15 次",
      status: "需要关注",
      description: "疑似气流明显减弱或暂停的事件。",
      reference: "持续出现时建议咨询睡眠医学或呼吸科。",
      roleExplanations: {
        elder: "夜里有几次呼吸不够顺，先观察是否经常出现。",
        family: "如果同时有明显打鼾、憋醒或白天困倦，应提高关注。",
        doctor: "Suspected apnea events=15，建议结合原始 airflow 和 effort 通道确认。",
      },
    },
    {
      key: "hypopnea",
      label: "低通气",
      value: "27 次",
      status: "需要关注",
      description: "呼吸变浅并可能伴随血氧下降的事件。",
      reference: "需要结合血氧和白天症状判断。",
      roleExplanations: {
        elder: "有些时候呼吸变浅，但这次血氧最低值还算稳定。",
        family: "低通气次数多于疑似暂停，建议观察鼾声、翻身和憋醒。",
        doctor: "Hypopnea events=27，需结合 desaturation/arousal 标准复核。",
      },
    },
    {
      key: "spo2",
      label: "最低 SpO2",
      value: "94.2%",
      status: "稳定",
      description: "夜间血氧最低估计值。",
      reference: "若明显偏低或伴随症状，应及时咨询医生。",
      roleExplanations: {
        elder: "这次最低血氧没有明显偏低，是一个相对安心的信号。",
        family: "当前未见明显低氧，但后续仍要看是否连续下降。",
        doctor: "Min SpO2≈94.2%，单晚结果未提示显著 desaturation。",
      },
    },
  ],
  evidence: [
    {
      title: "AHI 达到轻度异常范围",
      body: "本次 AHI 为 5.94，是系统给出中等风险提示的主要证据。",
      severity: "warning",
    },
    {
      title: "异常事件数量需要关注",
      body: "检测到疑似呼吸暂停 15 次、低通气 27 次，提示夜间呼吸稳定性下降。",
      severity: "warning",
    },
    {
      title: "血氧暂未出现明显低值",
      body: "最低 SpO2 约 94.2%，当前不提示明显低氧，但仍应连续观察趋势。",
      severity: "neutral",
    },
    {
      title: "单晚结果不能替代诊断",
      body: "系统建议结合连续多晚数据、白天症状和医生意见进一步判断。",
      severity: "neutral",
    },
  ],
  agentSteps: [
    {
      id: "01",
      planTitle: "读取 PSG 数据",
      agent: "数据读取 Agent",
      status: "done",
      elapsedMs: 620,
      inputSummary: "读取 SHHS / PSG 演示记录、用户基础信息和 480 分钟记录窗口。",
      outputFinding: "已读取 480 分钟记录，采样通道与基础元数据完整。",
      tools: [
        {
          name: "PSG Metadata Reader",
          type: "data",
          latencyMs: 240,
          detail: "解析记录 ID、记录时长、采样通道和基础人口学信息。",
        },
      ],
    },
    {
      id: "02",
      planTitle: "检查数据质量",
      agent: "质量检查 Agent",
      status: "done",
      elapsedMs: 740,
      inputSummary: "检查 EEG / EOG / EMG、Airflow、胸腹呼吸努力和 SpO2 通道可用性。",
      outputFinding: "数据质量可用于本次演示分析，未发现需要中止的缺失通道。",
      tools: [
        {
          name: "Signal Quality Gate",
          type: "validator",
          latencyMs: 360,
          detail: "检查记录时长、关键通道存在性和基础异常值范围。",
        },
      ],
    },
    {
      id: "03",
      planTitle: "识别睡眠阶段",
      agent: "睡眠分期 Agent",
      status: "done",
      elapsedMs: 1180,
      inputSummary: "EEG / EOG / EMG epoch 序列。",
      outputFinding: "识别 Wake / REM / NREM，睡眠效率 88.4%。",
      tools: [
        {
          name: "YASA Adapter",
          type: "model",
          latencyMs: 820,
          detail: "适配睡眠分期结果并聚合成 SleepAgent 摘要。",
        },
      ],
    },
    {
      id: "04",
      planTitle: "检测呼吸异常",
      agent: "呼吸事件检测 Agent",
      status: "done",
      elapsedMs: 1640,
      inputSummary: "Airflow、胸腹呼吸努力、SpO2 趋势和候选事件窗口。",
      outputFinding: "检测到疑似呼吸暂停 15 次、低通气 27 次，AHI 约 5.94。",
      tools: [
        {
          name: "1D-CNN + BiLSTM Boundary",
          type: "model",
          latencyMs: 1120,
          detail: "当前为 MVP 边界，后续可替换为真实模型推理服务。",
        },
        {
          name: "Respiratory Event Extractor",
          type: "parser",
          latencyMs: 280,
          detail: "聚合事件类型、起止时间、置信度和血氧下降。",
        },
      ],
    },
    {
      id: "05",
      planTitle: "检索医学知识",
      agent: "医学知识检索 Agent",
      status: "done",
      elapsedMs: 760,
      inputSummary: "AHI、睡眠效率、血氧、异常事件和风险等级。",
      outputFinding: "已检索 AHI 解释、OSA 风险提示和就医安全边界。",
      tools: [
        {
          name: "Local Medical Knowledge",
          type: "retrieval",
          latencyMs: 430,
          detail: "从本地知识片段检索报告依据。",
        },
      ],
    },
    {
      id: "06",
      planTitle: "生成多角色报告",
      agent: "报告生成 Agent",
      status: "done",
      elapsedMs: 920,
      inputSummary: "模型结果、医学依据、目标角色和安全声明。",
      outputFinding: "已生成老人、家属、医生、技术说明四类报告。",
      tools: [
        {
          name: "Role Report Formatter",
          type: "generation",
          latencyMs: 610,
          detail: "按角色调整语言密度、行动建议和专业程度。",
        },
      ],
    },
    {
      id: "07",
      planTitle: "准备问答上下文",
      agent: "对话问答 Agent",
      status: "done",
      elapsedMs: 540,
      inputSummary: "用户追问、本次记录摘要和安全边界。",
      outputFinding: "已准备本次记录上下文，可回答风险原因、就医建议、报告解读和趋势变化。",
      tools: [
        {
          name: "Dialogue Context Builder",
          type: "agent",
          latencyMs: 310,
          detail: "将本次记录摘要注入问答上下文。",
        },
      ],
    },
  ],
  reports: [
    {
      id: "elder",
      title: "老人易懂版",
      audience: "给老人本人阅读",
      focus: "用简单语言说明风险，强调安心、观察和今天能做的事。",
      summary: "昨晚整体睡眠还可以，但系统发现一些呼吸不稳定的信号。先不用过度紧张，建议连续观察几晚。",
      preview: [
        "本次记录显示，您大多数时间睡得比较连续。",
        "夜里有一些呼吸变浅或暂停的片段，所以 SleepAgent 提醒需要观察。",
        "这次最低血氧没有明显偏低。建议先连续观察几晚，如果经常憋醒或白天很困，再请家人一起咨询医生。",
      ],
      highlights: ["用词简单", "强调安心和观察", "突出今天能做的事情"],
      actions: ["尽量侧卧睡眠。", "避免睡前饮酒和过饱。", "如果经常憋醒或白天犯困，告诉家人一起关注。"],
      operations: ["预览", "下载 PDF", "复制摘要", "发送给家属"],
    },
    {
      id: "family",
      title: "家属照护版",
      audience: "给子女或照护者阅读",
      focus: "明确观察指标、陪同就医条件和家庭照护动作。",
      summary: "本次记录提示中等风险。建议关注老人是否伴随明显打鼾、憋醒或白天困倦，并连续观察 3 到 7 晚。",
      preview: [
        "本次 AHI 约 5.9，疑似呼吸暂停 15 次、低通气 27 次。",
        "建议家属连续观察 3 到 7 晚，记录打鼾、憋醒、晨起头痛、白天困倦等情况。",
        "若风险连续升高或症状明显，建议预约睡眠医学或呼吸科咨询，并携带医生版摘要。",
      ],
      highlights: ["强调趋势", "强调照护提醒", "提示陪同就医条件"],
      actions: ["记录夜间打鼾和憋醒频率。", "关注白天精神状态。", "若连续多晚异常，预约睡眠医学或呼吸科咨询。"],
      operations: ["预览", "下载 PDF", "复制摘要", "生成给家属的微信式摘要", "发送给家属", "生成医生就诊摘要"],
    },
    {
      id: "doctor",
      title: "医生专业版",
      audience: "给医生或临床沟通使用",
      focus: "保留关键 PSG 指标、事件统计和谨慎解释，不出现调试变量。",
      summary:
        "AHI 5.94，睡眠效率 88.4%，疑似呼吸暂停 15 次，低通气 27 次，最低 SpO2 94.2%。建议结合完整 PSG 与临床症状判断。",
      preview: [
        "患者：张阿姨，68 岁。记录日期：2026-01-02。PSG 记录时长 480 分钟，总睡眠约 424.5 分钟。",
        "自动分析：AHI 5.94/h，suspected apnea 15 次，hypopnea 27 次，min SpO2 94.2%，sleep efficiency 88.4%。",
        "建议结合原始 PSG、事件分布、睡姿、BMI、打鼾/憋醒/日间嗜睡等信息综合判断；本摘要仅作辅助沟通。",
      ],
      highlights: ["指标完整", "避免诊断化表述", "便于门诊沟通"],
      actions: ["结合完整 PSG 和症状判断。", "查看异常事件时间分布。", "必要时复测或进行临床评估。"],
      operations: ["预览", "下载 PDF", "复制摘要", "生成医生就诊摘要"],
    },
    {
      id: "technical",
      title: "技术说明版",
      audience: "给系统演示、答辩或开发联调用",
      focus: "说明 mock 边界、payload、模型和后续接口替换点。",
      summary: "当前前端使用本地 mock 数据模拟 Agent 编排、报告生成、证据链和对话追问流程。",
      preview: [
        "数据来源：frontend/lib/mock-data.ts，本次不调用真实 PDF、消息推送或后端持久化服务。",
        "Agent 流程：线性模拟数据读取、质量检查、睡眠分期、呼吸事件检测、医学知识检索、报告生成和问答上下文准备。",
        "后续可在 frontend/lib/api.ts 替换为 FastAPI /mock-analysis 与 /agent/orchestrate 响应。",
      ],
      highlights: ["展示架构", "说明 mock 边界", "保留后续接 API 的入口"],
      actions: ["接入 /mock-analysis。", "接入 /agent/orchestrate。", "替换 mock 数据为真实接口响应。"],
      operations: ["预览", "复制摘要", "下载原始分析数据 CSV", "生成答辩展示版技术说明", "查看 payload", "查看模型信息"],
      technicalDetails: [
        "mockPayload: sleepAnalysis",
        "modelBoundary: YASA Adapter + 1D-CNN/BiLSTM prototype",
        "frontendOnly: true",
      ],
    },
  ],
  trend: [
    { night: "D-6", ahi: 7.1, sleepEfficiency: 84, meanSpo2: 95.0, minSpo2: 93.8, apneaCount: 18, hypopneaCount: 31, risk: "moderate" },
    { night: "D-5", ahi: 6.8, sleepEfficiency: 85, meanSpo2: 95.2, minSpo2: 94.0, apneaCount: 17, hypopneaCount: 29, risk: "moderate" },
    { night: "D-4", ahi: 4.8, sleepEfficiency: 89, meanSpo2: 96.0, minSpo2: 94.8, apneaCount: 9, hypopneaCount: 24, risk: "low" },
    { night: "D-3", ahi: 5.2, sleepEfficiency: 88, meanSpo2: 95.8, minSpo2: 94.5, apneaCount: 12, hypopneaCount: 25, risk: "moderate" },
    { night: "D-2", ahi: 6.1, sleepEfficiency: 86, meanSpo2: 95.5, minSpo2: 94.0, apneaCount: 15, hypopneaCount: 29, risk: "moderate" },
    { night: "D-1", ahi: 5.7, sleepEfficiency: 87, meanSpo2: 95.6, minSpo2: 94.3, apneaCount: 14, hypopneaCount: 27, risk: "moderate" },
    { night: "本次", ahi: 5.94, sleepEfficiency: 88.4, meanSpo2: 95.7, minSpo2: 94.2, apneaCount: 15, hypopneaCount: 27, risk: "moderate" },
  ],
  respirationTrend: [
    { minute: 0, clockTime: "22:30", breathingRate: 13.8, spo2: 96.2, sleepStage: "Wake" },
    { minute: 45, clockTime: "23:15", breathingRate: 14.6, spo2: 95.8, event: "低通气", sleepStage: "NREM" },
    { minute: 90, clockTime: "00:00", breathingRate: 15.1, spo2: 95.5, sleepStage: "NREM" },
    { minute: 135, clockTime: "00:45", breathingRate: 13.2, spo2: 94.6, event: "疑似呼吸暂停", sleepStage: "REM" },
    { minute: 180, clockTime: "01:30", breathingRate: 14.7, spo2: 95.4, sleepStage: "NREM" },
    { minute: 225, clockTime: "02:15", breathingRate: 15.4, spo2: 95.1, event: "低通气", sleepStage: "REM" },
    { minute: 270, clockTime: "03:00", breathingRate: 13.9, spo2: 96.0, sleepStage: "NREM" },
    { minute: 315, clockTime: "03:45", breathingRate: 13.1, spo2: 95.7, sleepStage: "NREM" },
    { minute: 360, clockTime: "04:30", breathingRate: 14.4, spo2: 95.2, event: "低通气", sleepStage: "REM" },
    { minute: 405, clockTime: "05:15", breathingRate: 13.5, spo2: 95.9, sleepStage: "NREM" },
    { minute: 480, clockTime: "06:30", breathingRate: 14.2, spo2: 96.1, sleepStage: "Wake" },
  ],
  sleepStages: [
    { minute: 0, clockTime: "22:30", stage: "Wake", stageValue: 2 },
    { minute: 30, clockTime: "23:00", stage: "NREM", stageValue: 0 },
    { minute: 90, clockTime: "00:00", stage: "NREM", stageValue: 0 },
    { minute: 120, clockTime: "00:30", stage: "REM", stageValue: 1 },
    { minute: 150, clockTime: "01:00", stage: "NREM", stageValue: 0 },
    { minute: 210, clockTime: "02:00", stage: "REM", stageValue: 1 },
    { minute: 240, clockTime: "02:30", stage: "NREM", stageValue: 0 },
    { minute: 330, clockTime: "04:00", stage: "NREM", stageValue: 0 },
    { minute: 360, clockTime: "04:30", stage: "REM", stageValue: 1 },
    { minute: 420, clockTime: "05:30", stage: "NREM", stageValue: 0 },
    { minute: 465, clockTime: "06:15", stage: "Wake", stageValue: 2 },
  ],
  rawDataRows: [
    { minute: 0, clockTime: "22:30", breathingRate: 13.8, spo2: 96.2, sleepStage: "Wake", event: "正常" },
    { minute: 45, clockTime: "23:15", breathingRate: 14.6, spo2: 95.8, sleepStage: "NREM", event: "低通气" },
    { minute: 90, clockTime: "00:00", breathingRate: 15.1, spo2: 95.5, sleepStage: "NREM", event: "正常" },
    { minute: 135, clockTime: "00:45", breathingRate: 13.2, spo2: 94.6, sleepStage: "REM", event: "疑似呼吸暂停" },
    { minute: 180, clockTime: "01:30", breathingRate: 14.7, spo2: 95.4, sleepStage: "NREM", event: "正常" },
    { minute: 225, clockTime: "02:15", breathingRate: 15.4, spo2: 95.1, sleepStage: "REM", event: "低通气" },
    { minute: 270, clockTime: "03:00", breathingRate: 13.9, spo2: 96.0, sleepStage: "NREM", event: "正常" },
    { minute: 315, clockTime: "03:45", breathingRate: 13.1, spo2: 95.7, sleepStage: "NREM", event: "正常" },
    { minute: 360, clockTime: "04:30", breathingRate: 14.4, spo2: 95.2, sleepStage: "REM", event: "低通气" },
    { minute: 405, clockTime: "05:15", breathingRate: 13.5, spo2: 95.9, sleepStage: "NREM", event: "正常" },
    { minute: 480, clockTime: "06:30", breathingRate: 14.2, spo2: 96.1, sleepStage: "Wake", event: "正常" },
  ],
  medicalEvidence: [
    {
      title: "AHI 风险分层",
      source: "本地 OSA 风险知识片段",
      excerpt: "AHI 5 到 15 通常可作为轻度异常范围参考，需结合症状和完整 PSG 判断。",
      relevance: "解释本次 AHI 5.94 为什么触发中等风险提示。",
    },
    {
      title: "单晚自动分析边界",
      source: "SleepAgent 安全表述规则",
      excerpt: "自动分析结果只能作为辅助沟通，不能替代医生诊断或完整临床评估。",
      relevance: "约束报告和问答不输出诊断化结论。",
    },
    {
      title: "家庭观察要点",
      source: "照护随访知识片段",
      excerpt: "连续观察打鼾、憋醒、日间嗜睡、血氧下降和 AHI 趋势，有助于判断是否需要就医咨询。",
      relevance: "支持 7 天关怀计划和家属提醒文案。",
    },
  ],
  modelInsights: [
    {
      label: "睡眠分期置信度",
      value: "0.82",
      explanation: "本次 hypnogram 用于产品演示，真实部署时应展示每个 epoch 的模型置信度。",
    },
    {
      label: "呼吸事件检测置信度",
      value: "0.76",
      explanation: "疑似暂停和低通气事件来自 mock 聚合结果，临床使用前需复核原始通道。",
    },
    {
      label: "主要风险贡献",
      value: "AHI + 事件数量",
      explanation: "AHI 5.94、疑似暂停 15 次、低通气 27 次共同构成本次风险提示。",
    },
  ],
  developerDetails: [
    { label: "Mock Request", value: "record_id=shhs1-200001; seed=20260102; duration=480min" },
    { label: "Raw Mock Payload", value: "frontend/lib/mock-data.ts::sleepAnalysis" },
    { label: "LangGraph Agent Trace", value: "linear mock orchestration, 7 productized steps" },
    { label: "RAG Retrieved Context", value: "local medical snippets: AHI, OSA boundary, family care" },
    { label: "Model Version", value: "YASA Adapter demo + 1D-CNN/BiLSTM prototype boundary" },
    { label: "Inference Time", value: "total mocked elapsed time 6.4s" },
    { label: "Database Record ID", value: "local-demo/shhs1-200001" },
    { label: "Docker / FastAPI Status", value: "not required for React mock prototype" },
  ],
  metricExplanations: [
    {
      metricKey: "ahi",
      title: "AHI",
      currentValue: "5.94",
      meaning: "AHI 表示每小时疑似呼吸暂停或低通气事件次数。",
      referenceRange: "一般低于 5 较稳定，5-15 可作为轻度异常范围参考。",
      riskMeaning: "本次 AHI 触达轻度异常区间，是中等风险提示的主要依据。",
      agentRationale: "SleepAgent 同时看到疑似暂停 15 次、低通气 27 次，因此建议连续观察趋势。",
    },
    {
      metricKey: "spo2",
      title: "最低 SpO2",
      currentValue: "94.2%",
      meaning: "SpO2 反映夜间血氧饱和度，最低值用于识别是否出现明显低氧。",
      referenceRange: "本原型将 94% 附近作为需要结合症状观察的边界。",
      riskMeaning: "本次最低值未提示明显低氧，但不能单独排除睡眠呼吸问题。",
      agentRationale: "血氧相对稳定，所以 SleepAgent 没有给出高风险，但仍建议跟踪 AHI 和症状。",
    },
    {
      metricKey: "efficiency",
      title: "睡眠效率",
      currentValue: "88.4%",
      meaning: "睡眠效率表示睡着时间占记录时间比例。",
      referenceRange: "大于 85% 通常说明睡眠连续性尚可。",
      riskMeaning: "本次睡眠效率较好，主要风险不来自睡眠时间不足。",
      agentRationale: "SleepAgent 将注意力集中在呼吸事件，而不是失眠或睡眠碎片化。",
    },
    {
      metricKey: "hypopnea",
      title: "低通气",
      currentValue: "27 次",
      meaning: "低通气表示呼吸变浅，可能伴随血氧下降或觉醒。",
      referenceRange: "需要结合 AHI、SpO2、觉醒和症状综合解释。",
      riskMeaning: "低通气次数多于疑似暂停，是本次呼吸不稳定的重要来源。",
      agentRationale: "SleepAgent 将低通气计入 AHI 并纳入中等风险解释。",
    },
  ],
  memory: {
    title: "张阿姨长期睡眠画像",
    profile: ["68 岁", "重点关注睡眠呼吸风险", "当前记录来自 SHHS / PSG 演示样例"],
    historicalPattern: ["最近 7 天 AHI 多在 5-8 区间", "低通气偶尔偏多", "睡眠效率整体良好"],
    currentFocus: ["呼吸稳定性", "打鼾和憋醒", "白天困倦", "是否需要连续观察或就医咨询"],
  },
  chatSuggestions: ["为什么是中等风险？", "需要去医院吗？", "AHI 是什么？", "这份报告怎么给医生看？", "最近一周趋势怎么样？"],
  chatMessages: [
    {
      role: "assistant",
      content: "我已读取本次睡眠记录，可以帮你解释风险原因、就医建议、报告解读和趋势变化。",
    },
  ],
  carePlan: {
    period: "未来 7 天",
    indicators: [
      "AHI 是否连续升高",
      "最低 SpO2 是否低于阈值",
      "疑似呼吸暂停是否增加",
      "是否有打鼾、憋醒、白天困倦",
    ],
    recipients: ["本人", "家属", "医生"],
    channels: ["站内提醒", "家属摘要", "医生就诊建议"],
    actions: ["开启 7 天观察计划", "生成家属提醒文案", "编辑提醒规则"],
  },
  sleepRecords: [
    {
      id: "shhs1-200001",
      date: "2026-01-02",
      duration: "480 分钟",
      risk: "moderate",
      status: "已分析",
      summary: "AHI 5.94，疑似暂停 15 次，低通气 27 次。",
    },
    {
      id: "shhs1-200001-d1",
      date: "2026-01-01",
      duration: "476 分钟",
      risk: "moderate",
      status: "已分析",
      summary: "AHI 5.70，血氧趋势稳定。",
    },
    {
      id: "shhs1-200001-d2",
      date: "2025-12-31",
      duration: "468 分钟",
      risk: "moderate",
      status: "已分析",
      summary: "AHI 6.10，建议继续观察。",
    },
    {
      id: "upload-new",
      date: "上传新记录",
      duration: "-",
      risk: "low",
      status: "待分析",
      summary: "支持后续接入本地 EDF/PSG 上传流程。",
    },
    {
      id: "import-shhs",
      date: "导入 SHHS 样例",
      duration: "样例",
      risk: "low",
      status: "样例可导入",
      summary: "从授权本地样例中选择一条记录进入分析。",
    },
  ],
};
