from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Protocol

from sleepagent.schemas import (
    Artifact,
    ArtifactStatus,
    ArtifactType,
    ArtifactVersion,
    SleepAgentTask,
)
from sleepagent.services.safety import check_artifact_safety


ARTIFACT_RECORDS_FILENAME = "artifacts.jsonl"
ARTIFACT_VERSIONS_FILENAME = "artifact_versions.jsonl"


class ArtifactNotFoundError(KeyError):
    """Raised when an artifact id is not present in the artifact repository."""


class ArtifactRepository(Protocol):
    def save_task_artifacts(
        self,
        task: SleepAgentTask,
        artifacts: list[Artifact],
    ) -> list[Artifact]:
        ...

    def get_artifact(self, artifact_id: str) -> Artifact:
        ...

    def list_artifacts(self, task_id: str) -> list[Artifact]:
        ...

    def revise_artifact(
        self,
        artifact_id: str,
        *,
        content: str,
        revision_instruction: str,
        created_by: str,
    ) -> tuple[Artifact, ArtifactVersion]:
        ...

    def confirm_artifact(
        self,
        artifact_id: str,
        *,
        confirmed_by: str,
    ) -> Artifact:
        ...

    def list_versions(self, artifact_id: str) -> list[ArtifactVersion]:
        ...


class LocalJsonlArtifactRepository:
    """Append-only local artifact store used for tests and no-Postgres demos."""

    def __init__(self, store_dir: str | Path) -> None:
        self.store_dir = Path(store_dir)
        self.store_dir.mkdir(parents=True, exist_ok=True)
        self.artifacts_path = self.store_dir / ARTIFACT_RECORDS_FILENAME
        self.versions_path = self.store_dir / ARTIFACT_VERSIONS_FILENAME

    def save_task_artifacts(
        self,
        task: SleepAgentTask,
        artifacts: list[Artifact],
    ) -> list[Artifact]:
        saved: list[Artifact] = []
        for artifact in artifacts:
            if self._has_artifact(artifact.id):
                saved.append(self.get_artifact(artifact.id))
                continue
            version = _build_artifact_version(
                artifact.id,
                content=artifact.content,
                artifact_type=artifact.type,
                version_number=1,
                revision_instruction="Initial artifact generated by task graph.",
                created_by=artifact.created_by_step_id,
            )
            hydrated = _hydrate_artifact_metadata(
                artifact,
                task=task,
                current_version_id=version.id,
                status=artifact.status,
            )
            self._append_json_line(self.versions_path, version.model_dump(mode="json"))
            self._append_json_line(self.artifacts_path, hydrated.model_dump(mode="json"))
            saved.append(hydrated)
        return saved

    def get_artifact(self, artifact_id: str) -> Artifact:
        artifact = self._latest_artifacts_by_id().get(artifact_id)
        if artifact is None:
            raise ArtifactNotFoundError(artifact_id)
        return artifact

    def list_artifacts(self, task_id: str) -> list[Artifact]:
        return [
            artifact
            for artifact in self._latest_artifacts_by_id().values()
            if artifact.task_id == task_id
        ]

    def revise_artifact(
        self,
        artifact_id: str,
        *,
        content: str,
        revision_instruction: str,
        created_by: str,
    ) -> tuple[Artifact, ArtifactVersion]:
        artifact = self.get_artifact(artifact_id)
        version_number = len(self.list_versions(artifact_id)) + 1
        version = _build_artifact_version(
            artifact_id,
            content=content,
            artifact_type=artifact.type,
            version_number=version_number,
            revision_instruction=revision_instruction,
            created_by=created_by,
        )
        updated = artifact.model_copy(
            update={
                "status": ArtifactStatus.REVISED,
                "content": content,
                "current_version_id": version.id,
                "updated_at": version.created_at,
            }
        )
        self._append_json_line(self.versions_path, version.model_dump(mode="json"))
        self._append_json_line(self.artifacts_path, updated.model_dump(mode="json"))
        return updated, version

    def confirm_artifact(
        self,
        artifact_id: str,
        *,
        confirmed_by: str,
    ) -> Artifact:
        _ = confirmed_by
        artifact = self.get_artifact(artifact_id)
        updated = artifact.model_copy(
            update={
                "status": ArtifactStatus.READY,
                "updated_at": datetime.now(timezone.utc),
            }
        )
        self._append_json_line(self.artifacts_path, updated.model_dump(mode="json"))
        return updated

    def list_versions(self, artifact_id: str) -> list[ArtifactVersion]:
        versions = [
            ArtifactVersion.model_validate(payload)
            for payload in self._iter_json_lines(self.versions_path)
            if payload.get("artifact_id") == artifact_id
        ]
        return sorted(versions, key=lambda version: version.version_number)

    def _has_artifact(self, artifact_id: str) -> bool:
        return artifact_id in self._latest_artifacts_by_id()

    def _latest_artifacts_by_id(self) -> dict[str, Artifact]:
        latest: dict[str, Artifact] = {}
        for payload in self._iter_json_lines(self.artifacts_path):
            artifact = Artifact.model_validate(payload)
            latest[artifact.id] = artifact
        return latest

    def _append_json_line(self, path: Path, payload: dict) -> None:
        with path.open("a", encoding="utf-8") as file:
            file.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + "\n")

    def _iter_json_lines(self, path: Path) -> list[dict]:
        if not path.exists():
            return []
        rows: list[dict] = []
        with path.open("r", encoding="utf-8") as file:
            for line in file:
                stripped = line.strip()
                if stripped:
                    rows.append(json.loads(stripped))
        return rows


def _hydrate_artifact_metadata(
    artifact: Artifact,
    *,
    task: SleepAgentTask,
    current_version_id: str,
    status: ArtifactStatus,
) -> Artifact:
    now = datetime.now(timezone.utc)
    return artifact.model_copy(
        update={
            "task_id": task.id,
            "subject_id": task.patient_id,
            "record_id": task.record_id,
            "current_version_id": current_version_id,
            "status": status,
            "created_at": artifact.created_at or now,
            "updated_at": artifact.updated_at or now,
        }
    )


def _build_artifact_version(
    artifact_id: str,
    *,
    content: str,
    artifact_type: ArtifactType,
    version_number: int,
    revision_instruction: str,
    created_by: str,
) -> ArtifactVersion:
    created_at = datetime.now(timezone.utc)
    safety_result = check_artifact_safety(content, artifact_type=artifact_type)
    return ArtifactVersion(
        id=f"{artifact_id}-v{version_number}",
        artifact_id=artifact_id,
        version_number=version_number,
        content=content,
        revision_instruction=revision_instruction,
        created_by=created_by,
        created_at=created_at,
        safety_review_status=safety_result.safety_review_status,
        blocked_reasons=safety_result.blocked_reasons,
        reviewed_at=safety_result.reviewed_at,
        reviewed_by=safety_result.reviewed_by,
    )
